### ISSUE TITLE
Abschlusspräsentation

### ISSUE THREAD

**Issue by sefischer** [semproj-tierversuche/meta#1]
Hier sammle ich alle Todos, die für die Abschlusspräsentation zu erledigen sind.

- [X] Vortragende festlegen (Alpay, Sedir, Daniel)
- [ ] Ein funktionierendes Beispiel mit guten Suchergebnissen vorbereiten
- [ ] Präsentationsfolien erstellen ([Google Slides hier](https://docs.google.com/presentation/d/1RibchfMCdzctaqrI3iyXDpIodwQk6vFcZ7k5kw0AaqA/edit?usp=sharing))
  - nicht sehr technisch (Vorschlag: kurzer technischer Teil zum Schluss)

**Comment by Alpayyil** [comment]
Google Präsentation:
[https://docs.google.com/presentation/d/1RibchfMCdzctaqrI3iyXDpIodwQk6vFcZ7k5kw0AaqA/edit?usp=sharing](url)
