### ISSUE TITLE
Todos für die Abschlusspräsentation

### ISSUE THREAD

**Issue by Alpayyil** [semproj-tierversuche/meta#2]
- [ ] [Folien](https://docs.google.com/presentation/d/1RibchfMCdzctaqrI3iyXDpIodwQk6vFcZ7k5kw0AaqA/edit?usp=sharing) bis Sonntag Nacht - Textmining, Datenbanken, ~~Sebastian~~

- [x] Annotations von Bio-c nach JSON konvertieren - Sebastian

- [ ] Middleware ruft Textmining mit mehreren Dokumenten auf - Middleware

- [x] befüllen der Datenbank inkl. Annotations - Sebastian

- [ ] Auswertung der Annotations von der Datenbank - Datenbank

- [ ] Annotations/Mesh-headings markieren - Frontend

**Comment by sefischer** [comment]
@Alpayyil macht Web keine Folien?

**Comment by Alpayyil** [comment]
Nur eine Demo Folie
